project:
  type: book

book:
  title: "Computer Networks"
  subtitle: "Course Notes"
  author: 
    - name: "K. R. Kaza"
      affiliation: "IIIT Allahabad"
  date: "May 2026"
  chapters:
    - index.qmd
    - intro.qmd
    - physical-layer.qmd
    - link-layer.qmd
    - network-layer.qmd
    #- summary.qmd   git add link-layer.qmd _quarto.yml

    #- references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
    # documentclass: scrreprt



